### PR TITLE
Merge Cse gateway into Api gateway

### PR DESCRIPTION
**Pull request by marcvdm**
I merged the CSE Gateway into the API gateway because the cse features belong to the API gateway

Before in order to use CSE with a checkout i had to use 2 separate gateways, now i just have to use the single API gateway.

I am going to rely heavily on this package so i would like to contribute to this package.

### CODE REVIEW

**Comment by judgej** [comment]
Is there any reason why you didn't just copy the back-end methods you needed from `ApiGateway.php` to `CseGateway.php`, instead of removing `CseGateway.php` completely? Many gateways do that, where they have different front ends but share a common back-end.

If CSE is a superset of API, then `CseGateway.php` could just extend `ApiGateway.php`. There are other differences between the two gateway APIs that have not yet been put into code yet (the documentation is *vast* and there are still many gaps to be filled in, so I feel merging CSE and API is a little premature at this stage).

**Comment by marcvdm** [comment]
This is because the cse integration is only a front end thing. On the server side instead of providing the card details you provide the encrypted data. Then the AuthorizeRequest will inject the `card.encrypted.data` into `additionalData` instead of the card itself.

Off course we could extend the `ApiGateway.php` but this functionality is only specific to the ApiGateway and the only extra thing it provides is the EncryptionClient for front-end.

Here an example of my implementation
```
$authorize = Omnipay::create('Adyen\Api')->authorize();
$authorize->setEncryptedData($request->input('encrypted_data'));
...
$response = $authorize->send();
```

The rest of the request and response are exactly the same for both Cse and Api

Here an example of normal use
```
$authorize = Omnipay::create('Adyen\Api')->authorize();
$authorize->setCard(new CreditCard($request->get('card')));
...
$response = $authorize->send();
```

Because the client side implementation is specific therefore the server side implementation is that also.

**Comment by judgej** [comment]
I'm still not clear on this. Is CSE a super-set of API? If it is, then can CSE not simple extend API?

**Comment by judgej** [comment]
Does the latest `dev-master` commit give you what you need?

**Comment by marcvdm** [comment]
Thanks, it does give me what i want in the end!

Side note: The package is not yet published on packagist so the command `composer require academe/omnipay-adyen` does not work yet.

**Comment by judgej** [comment]
I'll get it released soon. Just needed to sort a few things out first.

(Hopefully this weekend, with a release straight to v3.0.0 so we track the Omnipay major version number.)

**Pull request closed without merging**
